// Copyright 2024 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Service to manage the conversation flow of the exploration player,
 * controlling behaviours such as adding cards to the stack, or submitting the
 * answer to progress further.
 */

import {StateCard} from 'domain/state_card/state-card.model';
import {Injectable} from '@angular/core';
import {ContentTranslationLanguageService} from './content-translation-language.service';
import {ContentTranslationManagerService} from './content-translation-manager.service';
import {ExplorationPlayerStateService} from './exploration-player-state.service';
import {StoryViewerDomainConstants} from 'domain/story_viewer/story-viewer-domain.constants';
import INTERACTION_SPECS from 'interactions/interaction_specs.json';
import {PlayerTranscriptService} from './player-transcript.service';
import { WindowRef } from 'services/contextual/window-ref.service';
import { MessengerService } from 'services/messenger.service';
import { ServicesConstants } from 'services/services.constants';
import { LoaderService } from 'services/loader.service';
import { ExplorationPlayerConstants } from '../exploration-player-page.constants';
import { VoiceoverPlayerService } from './voiceover-player.service';
import {AppConstants} from 'app.constants';
import { PlayerPositionService } from './player-position.service';
import { LearnerDashboardBackendApiService } from 'domain/learner_dashboard/learner-dashboard-backend-api.service';
import { CollectionPlayerBackendApiService } from 'pages/collection-player-page/services/collection-player-backend-api.service';
import { AlertsService } from 'services/alerts.service';
import { ExplorationEngineService } from './exploration-engine.service';
import { I18nLanguageCodeService, TranslationKeyType } from 'services/i18n-language-code.service';
import { WindowDimensionsService } from 'services/contextual/window-dimensions.service';
import { CurrentInteractionService } from './current-interaction.service';
import { StatsReportingService } from './stats-reporting.service';
import { ContextService } from 'services/context.service';
import { FetchExplorationBackendResponse, ReadOnlyExplorationBackendApiService } from 'domain/exploration/read-only-exploration-backend-api.service';
import { EditableExplorationBackendApiService } from 'domain/exploration/editable-exploration-backend-api.service';
import { AudioPlayerService } from 'services/audio-player.service';
import { AutogeneratedAudioPlayerService } from 'services/autogenerated-audio-player.service';
import { FocusManagerService } from 'services/stateful/focus-manager.service';
import { LearnerAnswerInfoService } from './learner-answer-info.service';
import {TopicViewerDomainConstants} from 'domain/topic_viewer/topic-viewer-domain.constants';
import {LearnerExplorationSummary} from 'domain/summary/learner-exploration-summary.model';
import { FatigueDetectionService } from './fatigue-detection.service';
import { UrlService } from 'services/contextual/url.service';
import { StoryViewerBackendApiService } from 'domain/story_viewer/story-viewer-backend-api.service';
import { UrlInterpolationService } from 'domain/utilities/url-interpolation.service';
import { UserService } from 'services/user.service';
import {StateObjectsBackendDict} from 'domain/exploration/StatesObjectFactory';
import { ExplorationRecommendationsService } from './exploration-recommendations.service';
import { DiagnosticTestTopicTrackerModel } from 'pages/diagnostic-test-player-page/diagnostic-test-topic-tracker.model';
import { QuestionPlayerConfigDict } from 'pages/exploration-player-page/services/exploration-player-state.service';
import { QuestionPlayerStateService } from 'components/question-directives/question-player/services/question-player-state.service';
import { AudioTranslationLanguageService } from './audio-translation-language.service';
import { ConceptCard } from 'domain/skill/concept-card.model';
import { NumberAttemptsService } from './number-attempts.service';
import { ConceptCardManagerService } from './concept-card-manager.service';
import { HintsAndSolutionManagerService } from './hints-and-solution-manager.service';
import { ConceptCardBackendApiService } from 'domain/skill/concept-card-backend-api.service';
import { RefresherExplorationConfirmationModalService } from './refresher-exploration-confirmation-modal.service';
import { ExplorationSummaryBackendApiService } from 'domain/summary/exploration-summary-backend-api.service';
import { InteractionRulesService } from './answer-classification.service';
import { QuestionPlayerEngineService } from './question-player-engine.service';
import { LearnerParamsService } from './learner-params.service';
import { BindableVoiceovers } from 'domain/exploration/recorded-voiceovers.model';
import { DiagnosticTestPlayerEngineService } from './diagnostic-test-player-engine.service';
import { TranslateService } from '@ngx-translate/core';
import { Solution } from 'domain/exploration/SolutionObjectFactory';
import { LocalStorageService } from 'services/local-storage.service';

@Injectable({
  providedIn: 'root',
})
export class ConversationFlowService {
  // If the exploration is iframed, send data to its parent about
  // its height so that the parent can be resized as necessary.
  lastRequestedHeight: number = 0;
  lastRequestedScroll: boolean = false;

  visitedStateNames: string[] = [];
  displayedCard: StateCard;
  isAnimatingToOneCard: boolean;
  isAnimatingToTwoCards: boolean;
  explorationId: string;
  isInPreviewMode: boolean;
  mostRecentlyReachedCheckpoint: string;
  responseTimeout: NodeJS.Timeout | null = null;
  numberOfIncorrectSubmissions: number = 0;
  inStoryMode: boolean = false;
  hasInteractedAtLeastOnce: boolean = false;
  isRefresherExploration: boolean;
  solutionForState: Solution | null = null;
  pendingCardWasSeenBefore: boolean = false;
  moveToExploration: boolean;
  showInteraction: boolean = true;
  collectionSummary: string[] | null = null;
  isLoggedIn: boolean;
  progressClearanceMessageIsShowed: boolean = false;
  storyNodeIdToAdd: string;
  // 'completedChaptersCount' is fetched via a HTTP request.
  // Until the response is received, it remains undefined.
  completedChaptersCount: number | undefined;
  answerIsBeingProcessed: boolean = false;
  chapterIsCompletedForTheFirstTime: boolean = false;
  recommendedExplorationSummaries = [];
  continueToReviseStateButtonIsVisible: boolean = false;
  parentExplorationIds: string[];
  questionSessionCompleted: boolean;
  explorationActuallyStarted: boolean = false;
  pidInUrl: string;
  redirectToRefresherExplorationConfirmed: boolean;
  answerIsCorrect: boolean = false;
  prevSessionStatesProgress: string[] = [];
  conceptCard: ConceptCard;
  isIframed: boolean;
  nextFocusLabel = null;
  hasFullyLoaded = false;
  editorPreviewMode: boolean;
  nextCardIfStuck: StateCard | null;
  correctnessFooterIsShown: boolean = true;
  startCardChangeAnimation: boolean;
  nextCard: StateCard;
  collectionId: string;

  constructor(
    private windowRef: WindowRef,
    private urlService: UrlService,
    private localStorageService: LocalStorageService,
    private translateService: TranslateService,
    private numberAttemptsService: NumberAttemptsService,
    private audioTranslationLanguageService: AudioTranslationLanguageService,
    private messengerService: MessengerService,
    private hintsAndSolutionManagerService: HintsAndSolutionManagerService,
    private conceptCardManagerService: ConceptCardManagerService,
    private questionPlayerEngineService: QuestionPlayerEngineService,
    private i18nLanguageCodeService: I18nLanguageCodeService,
    private questionPlayerStateService: QuestionPlayerStateService,
    private explorationRecommendationsService: ExplorationRecommendationsService,
    private readOnlyExplorationBackendApiService: ReadOnlyExplorationBackendApiService,
    private editableExplorationBackendApiService: EditableExplorationBackendApiService,
    private audioPlayerService: AudioPlayerService,
    private learnerAnswerInfoService: LearnerAnswerInfoService,
    private urlInterpolationService: UrlInterpolationService,
    private explorationSummaryBackendApiService: ExplorationSummaryBackendApiService,
    private autogeneratedAudioPlayerService: AutogeneratedAudioPlayerService,
    private focusManagerService: FocusManagerService,
    private userService: UserService,
    private contextService: ContextService,
    private currentInteractionService: CurrentInteractionService,
    private fatigueDetectionService: FatigueDetectionService,
    private windowDimensionsService: WindowDimensionsService,
    private conceptCardBackendApiService: ConceptCardBackendApiService,
    private contentTranslationLanguageService: ContentTranslationLanguageService,
    private contentTranslationManagerService: ContentTranslationManagerService,
    private explorationPlayerStateService: ExplorationPlayerStateService,
    private explorationEngineService: ExplorationEngineService,
    private storyViewerBackendApiService: StoryViewerBackendApiService,
    private loaderService: LoaderService,
    private statsReportingService: StatsReportingService,
    private collectionPlayerBackendApiService: CollectionPlayerBackendApiService,
    private alertsService: AlertsService,
    private learnerParamsService: LearnerParamsService,
    private playerPositionService: PlayerPositionService,
    private learnerDashboardBackendApiService: LearnerDashboardBackendApiService,
    private playerTranscriptService: PlayerTranscriptService,
    private refresherExplorationConfirmationModalService: RefresherExplorationConfirmationModalService,
    private voiceoverPlayerService: VoiceoverPlayerService
  ) {}

  // ========================================INITIALIZE PAGE==========================================================================.

  initializeService(): void {
    this.explorationId = this.explorationEngineService.getExplorationId();
    this.isInPreviewMode = this.explorationEngineService.isInPreviewMode();
    this.collectionId = this.urlService.getCollectionIdFromExplorationUrl();
    this.isIframed = this.urlService.isIframed();
    this.editorPreviewMode = this.contextService.isInExplorationEditorPage();
    this.pidInUrl = this.urlService.getPidFromUrl();

    this.userService.getUserInfoAsync().then(userInfo => {
      this.isLoggedIn = userInfo.isLoggedIn();
    });
  }

  initializePage(questionPlayerConfig: QuestionPlayerConfigDict, diagnosticTestTopicTrackerModel: DiagnosticTestTopicTrackerModel): void {
    this.hasInteractedAtLeastOnce = false;
    this.playerPositionService.init(this.navigateToDisplayedCard.bind(this));
    if (questionPlayerConfig) {
      this.explorationPlayerStateService.initializeQuestionPlayer(
        questionPlayerConfig,
        this.initializeDirectiveComponents.bind(this),
        this.showQuestionAreNotAvailable
      );
    } else if (diagnosticTestTopicTrackerModel) {
      this.explorationPlayerStateService.initializeDiagnosticPlayer(
        diagnosticTestTopicTrackerModel,
        this.initializeDirectiveComponents.bind(this)
      );
    } else {
      this.explorationPlayerStateService.initializePlayer(
        this.initializeDirectiveComponents.bind(this)
      );
    }
  }

  handleBeforeUnload(e: BeforeUnloadEvent): string | void {
    if (this.redirectToRefresherExplorationConfirmed) {
      return;
    }
    if (
      this.hasInteractedAtLeastOnce &&
      !this.isInPreviewMode &&
      !this.displayedCard.isTerminal() &&
      !this.explorationPlayerStateService.isInQuestionMode()
    ) {
      this.statsReportingService.recordMaybeLeaveEvent(
        this.playerTranscriptService.getLastStateName(),
        this.learnerParamsService.getAllParams()
      );

      let confirmationMessage =
        'Please save your progress before navigating away from the' +
        ' page; else, you will lose your exploration progress.';
      (e || this.windowRef.nativeWindow.event).returnValue =
        confirmationMessage;
      return confirmationMessage;
    }
  }

  fetchCompletedChaptersCount(): number {
    let completedChaptersCount = 0;
    this.learnerDashboardBackendApiService
      .fetchLearnerCompletedChaptersCountDataAsync()
      .then(data => {
        completedChaptersCount = data.completedChaptersCount;
      });
    return completedChaptersCount;
  }

  initializeCheckpointProgress(): void {
    if (
      !this.isIframed &&
      !this.editorPreviewMode &&
      !this.explorationPlayerStateService.isInQuestionPlayerMode() &&
      !this.explorationPlayerStateService.isInDiagnosticTestPlayerMode()
    ) {
      this.readOnlyExplorationBackendApiService
        .loadLatestExplorationAsync(this.explorationId, this.pidInUrl)
        .then(response => {
          this.handleCheckpointProgress(response);
        });
    }
  }

  handleCheckpointProgress(response: FetchExplorationBackendResponse): void {
    const expVersion = response.version;
    const firstStateName = response.exploration.init_state_name;
    this.mostRecentlyReachedCheckpoint =
      response.most_recently_reached_checkpoint_state_name;

    if (!this.mostRecentlyReachedCheckpoint && this.isLoggedIn) {
      this.editableExplorationBackendApiService.recordMostRecentlyReachedCheckpointAsync(
        this.explorationId,
        expVersion,
        firstStateName,
        true
      );
    }
    this.explorationPlayerStateService.setLastCompletedCheckpoint(firstStateName);
    this.visitedStateNames.push(firstStateName);
  }

  initializeCollectionAndChapterData(): void {
    if (this.collectionId) {
      this.collectionSummary = this.fetchCollectionSummary(
        this.collectionId
      );
    }

    if (this.isLoggedIn) {
      this.completedChaptersCount =
        this.fetchCompletedChaptersCount();
    }
  }

  async syncProgressOnLogin(): Promise<void> {
    let pid =
    this.localStorageService.getUniqueProgressIdOfLoggedOutLearner();
    if (pid && this.isLoggedIn) {
      await this.editableExplorationBackendApiService.changeLoggedOutProgressToLoggedInProgressAsync(
        this.explorationId,
        pid
      );
      this.localStorageService.removeUniqueProgressIdOfLoggedOutLearner();
    }
  }

  // =======================================================================================================================.

  adjustPageHeightOnresize(): void {
    this.windowRef.nativeWindow.onresize = () => {
      this.adjustPageHeight(false, null);
    };
  }

  adjustPageHeight(scroll: boolean, callback: () => void): void {
    setTimeout(() => {
      let newHeight = document.body.scrollHeight;
      if (
        Math.abs(this.lastRequestedHeight - newHeight) > 50.5 ||
        (scroll && !this.lastRequestedScroll)
      ) {
        // Sometimes setting iframe height to the exact content height
        // still produces scrollbar, so adding 50 extra px.
        newHeight += 50;
        this.messengerService.sendMessage(
          ServicesConstants.MESSENGER_PAYLOAD.HEIGHT_CHANGE,
          {
            height: newHeight,
            scroll: scroll,
          }
        );
        this.lastRequestedHeight = newHeight;
        this.lastRequestedScroll = scroll;
      }

      if (callback) {
        callback();
      }
    }, 100);
  }

  showQuestionAreNotAvailable(): void {
    this.loaderService.hideLoadingScreen();
  }

  getContentFocusLabel(index: number): string {
    return ExplorationPlayerConstants.CONTENT_FOCUS_LABEL_PREFIX + index;
  }

  isOnTerminalCard(): boolean {
    return this.displayedCard && this.displayedCard.isTerminal();
  }

  returnToExplorationAfterConceptCard(): void {
    this.playerTranscriptService.addPreviousCard();
    let numCards = this.playerTranscriptService.getNumCards();
    this.playerPositionService.setDisplayedCardIndex(numCards - 1);
  }

  // Returns whether the screen is wide enough to fit two
  // cards (e.g., the tutor and supplemental cards) side-by-side.
  canWindowShowTwoCards(): boolean {
    return (
      this.windowDimensionsService.getWidth() >
      ExplorationPlayerConstants.TWO_CARD_THRESHOLD_PX
    );
  }

  fetchCollectionSummary(collectionId: string): string[] | null {
    let collectionSummary = null;
    this.collectionPlayerBackendApiService
    .fetchCollectionSummariesAsync(collectionId)
    .then(
      response => {
        collectionSummary = response.summaries[0];
      },
      () => {
        this.alertsService.addWarning(
          'There was an error while fetching the collection ' + 'summary.'
        );
      }
    );
    return collectionSummary;
  }

  setActiveVoiceover(feedbackHtml: string): void {
    let interaction = this.displayedCard.getInteraction();

    let feedbackContentId =
      interaction.getContentIdForMatchingHtml(feedbackHtml);

    if (feedbackContentId) {
      this.voiceoverPlayerService.setActiveVoiceover(feedbackContentId);
    }
  }

  doesCollectionAllowsGuestProgress(collectionId: string | never): boolean {
    let allowedCollectionIds =
      AppConstants.ALLOWED_COLLECTION_IDS_FOR_SAVING_GUEST_PROGRESS;
    return (
      (allowedCollectionIds as readonly []).indexOf(collectionId as never) !==
      -1
    );
  }


  // ===============================================ADD CARD =============================================================.
  displayTranslationsIfNeeded(): void {
    const explorationLanguageCode = this.explorationPlayerStateService.getLanguageCode();
    const selectedLanguageCode = this.contentTranslationLanguageService.getCurrentContentLanguageCode();
    if (explorationLanguageCode !== selectedLanguageCode) {
      this.contentTranslationManagerService.displayTranslations(selectedLanguageCode);
    }
  }

  updateCurrentQuestion(): void {
    this.playerPositionService.changeCurrentQuestion(
      this.playerPositionService.getDisplayedCardIndex()
    );
  }

  updateDisplayedCardIndex(): void {
    let totalNumCards = this.playerTranscriptService.getNumCards();
    if (totalNumCards <= 1) {
      this.setDisplayedCardIndex(totalNumCards - 1);
      return;
    }

    const previousSupplementalCardIsNonempty = this.isSupplementalCardNonempty(
      this.playerTranscriptService.getCard(totalNumCards - 2)
    );
    const nextSupplementalCardIsNonempty = this.isSupplementalCardNonempty(
      this.playerTranscriptService.getLastCard()
    );

    if (this.canWindowShowTwoCards()) {
      if (!previousSupplementalCardIsNonempty && nextSupplementalCardIsNonempty) {
        this.setDisplayedCardIndex(totalNumCards - 1);
        this.animateToTwoCards(() => {});
      } else if (previousSupplementalCardIsNonempty && !nextSupplementalCardIsNonempty) {
        this.animateToOneCard(() => this.setDisplayedCardIndex(totalNumCards - 1));
      } else {
        this.setDisplayedCardIndex(totalNumCards - 1);
      }
    } else {
      this.setDisplayedCardIndex(totalNumCards - 1);
    }
  }

  setDisplayedCardIndex(index: number): void {
    this.playerPositionService.setDisplayedCardIndex(index);
  }

  showProgressClearanceMessage(): void {
    if (!this.progressClearanceMessageIsShowed) {
      this.progressClearanceMessageIsShowed = true;
      setTimeout(() => {
        let alertInfoElement = document.querySelector(
          '.oppia-exploration-checkpoints-message'
        );

        // Remove the alert message after 6 sec.
        if (alertInfoElement) {
          alertInfoElement.remove();
        }
      }, ExplorationPlayerConstants.ALERT_MESSAGE_TIMEOUT);
    }
  }

  handleStoryMode(isLoggedIn: boolean): void {
    const topicUrlFragment = this.urlService.getUrlParams().topic_url_fragment;
    const classroomUrlFragment = this.urlService.getUrlParams().classroom_url_fragment;
    const storyUrlFragment = this.urlService.getUrlParams().story_url_fragment;
    const nodeId = this.urlService.getUrlParams().node_id;

    this.inStoryMode = true;
    this.storyViewerBackendApiService.fetchStoryDataAsync(
      topicUrlFragment, classroomUrlFragment, storyUrlFragment).then(res => {
        let nextStoryNode: LearnerExplorationSummary[] = [];
        for (let i = 0; i < res.nodes.length; i++) {
            if (res.nodes[i].id === nodeId && i + 1 < res.nodes.length) {
                this.storyNodeIdToAdd = res.nodes[i].destinationNodeIds[0];
                nextStoryNode.push(res.nodes[i + 1].explorationSummary);
                break;
            }
        }
        this.recommendedExplorationSummaries = nextStoryNode;
    });

    // If the user is logged in, record chapter completion.
    if (isLoggedIn) {
        this.storyViewerBackendApiService.recordChapterCompletionAsync(
            topicUrlFragment,
            classroomUrlFragment,
            storyUrlFragment,
            nodeId
        ).then(returnObject => {
            // Check if the user is ready for a review test.
            if (returnObject.readyForReviewTest) {
              (
                this.windowRef.nativeWindow as {location: string | Location}
              ).location = this.urlInterpolationService.interpolateUrl(
                TopicViewerDomainConstants.REVIEW_TESTS_URL_TEMPLATE,
                {
                  topic_url_fragment: topicUrlFragment,
                  classroom_url_fragment: classroomUrlFragment,
                  story_url_fragment: storyUrlFragment,
                }
              );
            }

            // Fetch the completed chapters count.
            this.learnerDashboardBackendApiService.fetchLearnerCompletedChaptersCountDataAsync().then(responseData => {
                const newCompletedChaptersCount = responseData.completedChaptersCount;
                if (newCompletedChaptersCount !== this.completedChaptersCount) {
                    this.completedChaptersCount = newCompletedChaptersCount;
                    this.chapterIsCompletedForTheFirstTime = true;
                }
            });
        });
    } else {
        // If the user is not logged in, set the return URL for login.
        const loginRedirectUrl = this.urlInterpolationService.interpolateUrl(
            StoryViewerDomainConstants.STORY_PROGRESS_URL_TEMPLATE,
            {
                topic_url_fragment: topicUrlFragment,
                classroom_url_fragment: classroomUrlFragment,
                story_url_fragment: storyUrlFragment,
                node_id: nodeId,
            }
        );
        this.userService.setReturnUrl(loginRedirectUrl);
    }
  }

  getExplorationRecommendations(): { recommendedExplorationIds: string[]; includeAutogeneratedRecommendations: boolean } {
    let recommendedExplorationIds = [];
    let includeAutogeneratedRecommendations = false;
    this.isRefresherExploration = false;
    this.parentExplorationIds =
    this.urlService.getQueryFieldValuesAsList('parent');

    if (this.parentExplorationIds.length > 0) {
        this.isRefresherExploration = true;
        const parentExplorationId = this.parentExplorationIds[this.parentExplorationIds.length - 1];
        recommendedExplorationIds.push(parentExplorationId);
    } else {
        recommendedExplorationIds = this.explorationEngineService.getAuthorRecommendedExpIdsByStateName(
            this.displayedCard.getStateName()
        );
        includeAutogeneratedRecommendations = true;
    }

    return { recommendedExplorationIds, includeAutogeneratedRecommendations };
  }

  fetchRecommendedExplorations(recommendedExplorationIds: string[], includeAutogeneratedRecommendations: boolean): void {
    this.explorationRecommendationsService.getRecommendedSummaryDicts(
        recommendedExplorationIds,
        includeAutogeneratedRecommendations,
        summaries => {
            this.updateRecommendedExplorationSummaries(summaries);
        }
    );
}

  addNewCard(newCard: StateCard): void {
    this.playerTranscriptService.addNewCard(newCard);
    this.displayTranslationsIfNeeded();
    this.updateDisplayedCardIndex();
    this.updateCurrentQuestion();

  if (this.displayedCard && this.displayedCard.isTerminal()) {
      let { recommendedExplorationIds, includeAutogeneratedRecommendations } = this.getExplorationRecommendations();

      if (this.explorationPlayerStateService.isInStoryChapterMode()) {
        this.handleStoryMode(this.isLoggedIn);
      } else {
        this.fetchRecommendedExplorations(
          recommendedExplorationIds,
          includeAutogeneratedRecommendations
        );
      }

      this.showProgressClearanceMessage();
    }
  }

  // =============================================NAVIGATE TO MOST RECENT CHECKPOINT=======================================================================.

  addPreviousStatesToTranscript(): number {
    let indexToRedirectTo = 0;

    for (const stateName of this.prevSessionStatesProgress) {
        // Skip the card if it has already been added to the transcript.
        if (!this.playerTranscriptService.hasEncounteredStateBefore(stateName)) {
            const stateCard = this.explorationEngineService.getStateCardByName(stateName);
            this.addNewCard(stateCard);
        }

        if (this.mostRecentlyReachedCheckpoint === stateName) {
            break;
        }

        this.visitedStateNames.push(stateName);
        indexToRedirectTo += 1;
    }

    return indexToRedirectTo;
  }

  showCheckpointMessage(): void {
    setTimeout(() => {
        const alertInfoElement = document.querySelector('.oppia-exploration-checkpoints-message');

        // Remove the alert message after 6 seconds.
        if (alertInfoElement) {
            alertInfoElement.remove();
        }
    }, ExplorationPlayerConstants.ALERT_MESSAGE_TIMEOUT);
  }

  navigateToMostRecentlyReachedCheckpoint(): void {
    let states: StateObjectsBackendDict;
    this.readOnlyExplorationBackendApiService
      .loadLatestExplorationAsync(this.explorationId, this.pidInUrl)
      .then(response => {
        states = response.exploration.states;

        this.mostRecentlyReachedCheckpoint =
          response.most_recently_reached_checkpoint_state_name;

          this.prevSessionStatesProgress =
          this.explorationEngineService.getShortestPathToState(
            states,
            this.mostRecentlyReachedCheckpoint
        );

        let indexToRedirectTo = this.addPreviousStatesToTranscript();

        // Remove the last card from progress as it is not completed
        // yet and is only most recently reached.
        this.prevSessionStatesProgress.pop();

        if (indexToRedirectTo > 0) {
          this.showCheckpointMessage();
        }

        // Move to most recently reached checkpoint card.
        this.changeCard(indexToRedirectTo);
        this.playerPositionService.onLoadedMostRecentCheckpoint.emit();
      });
  }

  // ========================================INITINIALIZE DIRECTIVE COMPONENT==========================================================================.

  // If the exploration is embedded, use the url language code
  // as site language. If the url language code is not supported
  // as site language, English is used as default.
  setLanguageForIframedExploration(): void {
    const langCodes = AppConstants.SUPPORTED_SITE_LANGUAGES.map(language => language.id) as string[];
    if (this.isIframed) {
        const urlLanguageCode = this.urlService.getUrlParams().lang;
        if (urlLanguageCode && langCodes.includes(urlLanguageCode)) {
            this.i18nLanguageCodeService.setI18nLanguageCode(urlLanguageCode);
        } else {
            this.i18nLanguageCodeService.setI18nLanguageCode('en');
        }
    }
  }

  initializeDirectiveComponents(initialCard: StateCard, focusLabel: string): void {
    this.addNewCard(initialCard);
    this.nextCard = initialCard;
    if (!this.explorationPlayerStateService.isInDiagnosticTestPlayerMode()) {
      this.explorationPlayerStateService.onPlayerStateChange.emit(
        this.nextCard.getStateName()
      );
    }

    // We do not store checkpoints progress for iframes hence we do not
    // need to consider redirecting the user to the most recently
    // reached checkpoint on exploration initial load in that case.
    if (
      !this.isIframed &&
      !this.editorPreviewMode &&
      !this.explorationPlayerStateService.isInQuestionPlayerMode() &&
      !this.explorationPlayerStateService.isInDiagnosticTestPlayerMode()
    ) {
      // Navigate the learner to the most recently reached checkpoint state.
      this.navigateToMostRecentlyReachedCheckpoint();
    }
    this.hasFullyLoaded = true;

    this.focusManagerService.setFocusIfOnDesktop(focusLabel);
    this.loaderService.hideLoadingScreen();

    this.setLanguageForIframedExploration();
    this.adjustPageHeight(false, null);
    this.windowRef.nativeWindow.scrollTo(0, 0);

    // The timeout is needed in order to give the recipient of the
    // broadcast sufficient time to load.
    setTimeout(() => {
      this.playerPositionService.onNewCardOpened.emit(initialCard);
    });
  }

  // ===========================================SHOW PENDING CARDS===========================================================================.

    showPendingCard(): void {
      this.startCardChangeAnimation = true;
      this.explorationPlayerStateService.recordNewCardAdded();

      this.scheduleNewCardAddition();
      this.scheduleFocusAdjustment();
      this.scheduleAnimationCompletion();

      this.playerPositionService.onNewCardOpened.emit(this.nextCard);
  }

  private scheduleNewCardAddition(): void {
      setTimeout(() => {
          this.addNewCard(this.nextCard);
      }, 0.1 * ExplorationPlayerConstants.TIME_FADEOUT_MSEC + 0.1 * ExplorationPlayerConstants.TIME_HEIGHT_CHANGE_MSEC);
  }

  private scheduleFocusAdjustment(): void {
      setTimeout(() => {
          this.focusManagerService.setFocusIfOnDesktop(this.getNextFocusLabel());
          this.scrollToTop();
      }, 0.1 * ExplorationPlayerConstants.TIME_FADEOUT_MSEC + ExplorationPlayerConstants.TIME_HEIGHT_CHANGE_MSEC + 0.5 * ExplorationPlayerConstants.TIME_FADEIN_MSEC);
  }

  private scheduleAnimationCompletion(): void {
      setTimeout(() => {
          this.startCardChangeAnimation = false;
      }, 0.1 * ExplorationPlayerConstants.TIME_FADEOUT_MSEC + ExplorationPlayerConstants.TIME_HEIGHT_CHANGE_MSEC + ExplorationPlayerConstants.TIME_FADEIN_MSEC + ExplorationPlayerConstants.TIME_PADDING_MSEC);
  }

  scrollToTop(): void {
    setTimeout(() => {
      $('html, body').animate(
        {
          scrollTop: 0,
        },
        800,
        'easeOutQuart'
      );
      return false;
    });
  }


  // ====================================SHOW UPCOMING CARD==================================================================================.

  showUpcomingCard(): void {
    const currentIndex = this.playerPositionService.getDisplayedCardIndex();
    const isConceptCardBeingShown = this.isConceptCardBeingShown();

    if (isConceptCardBeingShown && this.playerTranscriptService.isLastCard(currentIndex)) {
        this.returnToExplorationAfterConceptCard();
        return;
    }

    if (this.questionSessionCompleted) {
        this.emitQuestionSessionCompleted();
        return;
    }

    if (this.moveToExploration) {
        this.handleMoveToExploration();
        return;
    }

    if (this.shouldAddConceptCard()) {
        this.addConceptCard();
        return;
    }

    if (this.isLearnAgainButton()) {
        this.handleLearnAgainButton();
        return;
    }

    this.updatePendingCardState();
    this.showPendingCard();
  }

  private isConceptCardBeingShown(): boolean {
      return this.displayedCard.getStateName() === null &&
            !this.explorationPlayerStateService.isInQuestionMode();
  }

  private emitQuestionSessionCompleted(): void {
      this.questionPlayerStateService.onQuestionSessionCompleted.emit(
          this.questionPlayerStateService.getQuestionPlayerStateData()
      );
  }

  private handleMoveToExploration(): void {
      this.moveToExploration = false;
      this.explorationPlayerStateService.moveToExploration(
          this.initializeDirectiveComponents.bind(this)
      );
  }

  private shouldAddConceptCard(): boolean {
      return this.displayedCard.isCompleted() &&
        this.nextCard.getStateName() === this.displayedCard.getStateName() &&
        !!this.conceptCard;
  }

  private addConceptCard(): void {
      this.explorationPlayerStateService.recordNewCardAdded();
      this.addNewCard(
          StateCard.createNewCard(
              null,
              this.conceptCard.getExplanation().html,
              null,
              null,
              null,
              null,
              this.audioTranslationLanguageService
          )
      );
  }

  private handleLearnAgainButton(): void {
      const indexOfRevisionCard = this.playerTranscriptService.findIndexOfLatestStateWithName(
          this.nextCard.getStateName()
      );

      if (indexOfRevisionCard !== null) {
          this.displayedCard.markAsNotCompleted();
          this.changeCard(indexOfRevisionCard);
      }
  }

  private updatePendingCardState(): void {
      if (this.answerIsCorrect) {
          this.pendingCardWasSeenBefore = false;
      }
      this.answerIsCorrect = false;
  }

  // ==========================================MOVE TO NEW CARD============================================================================.

  moveToNewCard(
    feedbackHtml: string | null,
    isFinalQuestion: boolean,
    nextCard: StateCard
  ): void {
      this.pendingCardWasSeenBefore = false;
      this.displayedCard.markAsCompleted();

      if (isFinalQuestion) {
          this.handleFinalQuestion(feedbackHtml);
          return;
      }

      this.fatigueDetectionService.reset();
      this.numberAttemptsService.reset();

      if (feedbackHtml) {
          this.handleFeedback(feedbackHtml, nextCard);
      } else {
          this.handleNoFeedback(nextCard);
      }

      this.currentInteractionService.clearPresubmitHooks();
  }

  private handleFinalQuestion(feedbackHtml: string | null): void {
      if (this.explorationPlayerStateService.isInQuestionPlayerMode()) {
          this.questionSessionCompleted = true;
      }
      this.moveToExploration = true;

      if (feedbackHtml) {
          this.playerTranscriptService.addNewResponse(feedbackHtml);
          this.showHelpCard(feedbackHtml);
      } else {
          this.showUpcomingCard();
      }

      this.answerIsBeingProcessed = false;
  }

  private handleFeedback(feedbackHtml: string, nextCard: StateCard): void {
      if (this.playerTranscriptService.hasEncounteredStateBefore(nextCard.getStateName())) {
          this.pendingCardWasSeenBefore = true;
      }
      this.playerTranscriptService.addNewResponse(feedbackHtml);
      this.showHelpCard(feedbackHtml);
      this.playerPositionService.onNewCardAvailable.emit();
      this.nextFocusLabel = ExplorationPlayerConstants.CONTINUE_BUTTON_FOCUS_LABEL;
      this.focusManagerService.setFocusIfOnDesktop(this.nextFocusLabel);
      this.scrollToBottom();
  }

  showHelpCard(feedbackHtml: string): void {
      if (!this.displayedCard.isInteractionInline()) {
          this.playerPositionService.onHelpCardAvailable.emit({
              helpCardHtml: feedbackHtml,
              hasContinueButton: true,
          });
      }
  }

  private handleNoFeedback(nextCard: StateCard): void {
      this.playerTranscriptService.addNewResponse(null);
      this.answerIsCorrect = false;
      this.showPendingCard();
  }

  scrollToBottom(): void {
    setTimeout(() => {
      let tutorCard = $('.conversation-skin-main-tutor-card');

      if (tutorCard && tutorCard.length === 0) {
        return;
      }
      let tutorCardBottom = tutorCard.offset().top + tutorCard.outerHeight();
      if ($(window).scrollTop() + $(window).height() < tutorCardBottom) {
        $('html, body').animate(
          {
            scrollTop: tutorCardBottom - $(window).height() + 12,
          },
          {
            duration: ExplorationPlayerConstants.TIME_SCROLL_MSEC,
            easing: 'easeOutQuad',
          }
        );
      }
    }, 100);
  }

  // ======================================GIVE FEEDBACK ON CURRENT CARD================================================================================.

  giveFeedbackAndStayOnCurrentCard(
    feedbackHtml: string | null,
    missingPrerequisiteSkillId: string | null,
    refreshInteraction: boolean,
    refresherExplorationId: string | null
  ): void {
      this.numberOfIncorrectSubmissions++;
      this.hintsAndSolutionManagerService.recordWrongAnswer();
      this.conceptCardManagerService.recordWrongAnswer();
      this.playerTranscriptService.addNewResponse(feedbackHtml);

      const helpCardAvailable = this.shouldShowHelpCard(feedbackHtml);

      if (helpCardAvailable) {
          this.showHelpCardForFeedback(feedbackHtml);
      }

      if (missingPrerequisiteSkillId) {
          this.handleMissingPrerequisiteSkill(missingPrerequisiteSkillId, helpCardAvailable, feedbackHtml);
      }

      if (refreshInteraction) {
          this.refreshInteraction();
      }

      this.redirectToRefresherExplorationConfirmed = false;

      if (refresherExplorationId) {
          this.handleRefresherExploration(refresherExplorationId);
      }

      this.focusManagerService.setFocusIfOnDesktop(this.nextFocusLabel);
      this.scrollToBottom();
  }

  private shouldShowHelpCard(feedbackHtml: string | null): boolean {
      return feedbackHtml && !this.displayedCard.isInteractionInline();
  }

  private showHelpCardForFeedback(feedbackHtml: string): void {
      this.playerPositionService.onHelpCardAvailable.emit({
          helpCardHtml: feedbackHtml,
          hasContinueButton: false,
      });
  }

  private handleMissingPrerequisiteSkill(missingPrerequisiteSkillId: string, helpCardAvailable: boolean, feedbackHtml: string | null): void {
      this.displayedCard.markAsCompleted();
      this.conceptCardBackendApiService.loadConceptCardsAsync([missingPrerequisiteSkillId]).then(conceptCardObject => {
          this.conceptCard = conceptCardObject[0];
          if (helpCardAvailable) {
              this.showHelpCardForFeedback(feedbackHtml);
          }
      });
  }

  private refreshInteraction(): void {
      this.nextFocusLabel = this.focusManagerService.generateFocusLabel();
      this.playerTranscriptService.updateLatestInteractionHtml(
          this.displayedCard.getInteractionHtml() + this.explorationEngineService.getRandomSuffix()
      );
  }

  private handleRefresherExploration(refresherExplorationId: string): void {
      const confirmRedirection = () => {
          this.redirectToRefresherExplorationConfirmed = true;
          this.recordLeaveForRefresherExp(refresherExplorationId);
      };

      this.explorationSummaryBackendApiService.loadPublicExplorationSummariesAsync([refresherExplorationId]).then(response => {
          if (response.summaries.length > 0) {
              this.refresherExplorationConfirmationModalService.displayRedirectConfirmationModal(
                  refresherExplorationId,
                  confirmRedirection
              );
          }
      });
  }

  // ===========================================SUBMIT ANSWER==============================================================================.


  submitAnswerFromProgressNav(): void {
    this.displayedCard.toggleSubmitClicked(true);
    this.currentInteractionService.submitAnswer();
  }

  submitAnswer(
    answer: string,
    interactionRulesService: InteractionRulesService
  ): void {
      // Safety check to prevent double submissions from occurring.
      if (this.isSubmissionInvalid()) {
          return;
      }

      this.handleFatigueDetection();

      if (this.shouldSolicitAnswerDetails()) {
          this.initLearnerAnswerInfoService(answer, interactionRulesService);
      }

      this.numberAttemptsService.submitAttempt();
      this.answerIsBeingProcessed = true;
      this.hasInteractedAtLeastOnce = true;
      this.playerTranscriptService.addNewInput(answer, false);

      if (this.getCanAskLearnerForAnswerInfo()) {
          this.handleSolicitAnswerDetails();
          return;
      }

      this.processAnswerSubmission(answer, interactionRulesService);
  }

  private isSubmissionInvalid(): boolean {
      return (
          this.answerIsBeingProcessed ||
          !this.isCurrentCardAtEndOfTranscript() ||
          this.displayedCard.isCompleted()
      );
  }

  private shouldSolicitAnswerDetails(): boolean {
      return (
          !this.isInPreviewMode &&
          !this.explorationPlayerStateService.isPresentingIsolatedQuestions() &&
          AppConstants.ENABLE_SOLICIT_ANSWER_DETAILS_FEATURE
      );
  }

  private initLearnerAnswerInfoService(answer: string, interactionRulesService: InteractionRulesService): void {
      this.learnerAnswerInfoService.initLearnerAnswerInfoService(
          this.explorationId,
          this.explorationEngineService.getState(),
          answer,
          interactionRulesService,
          this.alwaysAskLearnerForAnswerDetails()
      );
  }

  private handleSolicitAnswerDetails(): void {
      setTimeout(() => {
          this.playerTranscriptService.addNewResponse(
              this.learnerAnswerInfoService.getSolicitAnswerDetailsQuestion()
          );
          this.answerIsBeingProcessed = false;
          this.playerPositionService.onHelpCardAvailable.emit({
              helpCardHtml: this.learnerAnswerInfoService.getSolicitAnswerDetailsQuestion(),
              hasContinueButton: false,
          });
      }, 100);
  }

  private processAnswerSubmission(answer: string, interactionRulesService: InteractionRulesService): void {
      const timeAtServerCall = new Date().getTime();
      this.playerPositionService.recordAnswerSubmission();
      const currentEngineService = this.explorationPlayerStateService.getCurrentEngineService();

      this.answerIsCorrect = currentEngineService.submitAnswer(
          answer,
          interactionRulesService,
          (nextCard, refreshInteraction, feedbackHtml, feedbackAudioTranslations, refresherExplorationId, missingPrerequisiteSkillId, remainOnCurrentCard, taggedSkillMisconceptionId, wasOldStateInitial, isFirstHit, isFinalQuestion, nextCardIfReallyStuck, focusLabel) => {
              this.handleAnswerSubmissionResponse(nextCard, refreshInteraction, feedbackHtml, feedbackAudioTranslations, refresherExplorationId, missingPrerequisiteSkillId, remainOnCurrentCard, taggedSkillMisconceptionId, wasOldStateInitial, isFirstHit, isFinalQuestion, nextCardIfReallyStuck, answer, timeAtServerCall, currentEngineService);
          }
      );
  }

  private handleAnswerSubmissionResponse(
      nextCard: StateCard,
      refreshInteraction: boolean,
      feedbackHtml: string,
      feedbackAudioTranslations: BindableVoiceovers,
      refresherExplorationId: string | null,
      missingPrerequisiteSkillId: string | null,
      remainOnCurrentCard: boolean,
      taggedSkillMisconceptionId: string | null,
      wasOldStateInitial: boolean,
      isFirstHit: boolean,
      isFinalQuestion: boolean,
      nextCardIfReallyStuck: StateCard,
      answer: string,
      timeAtServerCall: number,
      currentEngineService: QuestionPlayerEngineService | ExplorationEngineService | DiagnosticTestPlayerEngineService
  ): void {
      this.nextCard = nextCard;
      this.nextCardIfStuck = nextCardIfReallyStuck;

      if (!this.editorPreviewMode && !this.explorationPlayerStateService.isPresentingIsolatedQuestions()) {
          this.recordStateTransition(nextCard, answer, isFirstHit, wasOldStateInitial, currentEngineService);
      }

      if (!this.explorationPlayerStateService.isPresentingIsolatedQuestions()) {
          this.explorationPlayerStateService.onPlayerStateChange.emit(nextCard.getStateName());
      } else if (this.explorationPlayerStateService.isInQuestionPlayerMode()) {
          this.questionPlayerStateService.answerSubmitted(
              this.questionPlayerEngineService.getCurrentQuestion(),
              !remainOnCurrentCard,
              taggedSkillMisconceptionId
          );
      }

      const millisecsLeftToWait = this.calculatePostSubmissionDelay(timeAtServerCall);

      setTimeout(() => {
          this.explorationPlayerStateService.onOppiaFeedbackAvailable.emit();
          this.setActiveVoiceover(feedbackHtml);
          this.voiceoverPlayerService.setActiveComponentName(AppConstants.COMPONENT_NAME_FEEDBACK);

          this.audioPlayerService.onAutoplayAudio.emit({
              audioTranslations: feedbackAudioTranslations,
              html: feedbackHtml,
              componentName: AppConstants.COMPONENT_NAME_FEEDBACK,
          });

          if (remainOnCurrentCard) {
              this.giveFeedbackAndStayOnCurrentCard(
                  feedbackHtml,
                  missingPrerequisiteSkillId,
                  refreshInteraction,
                  refresherExplorationId
              );
          } else {
              this.moveToNewCard(feedbackHtml, isFinalQuestion, nextCard);
          }
          this.answerIsBeingProcessed = false;
      }, millisecsLeftToWait);
  }

  private recordStateTransition(nextCard: StateCard, answer: string, isFirstHit: boolean, wasOldStateInitial: boolean, currentEngineService): void {
      const oldStateName = this.playerPositionService.getCurrentStateName();
      this.statsReportingService.recordStateTransition(
          oldStateName,
          nextCard.getStateName(),
          answer,
          this.learnerParamsService.getAllParams(),
          isFirstHit,
          String(this.completedChaptersCount && this.completedChaptersCount + 1),
          String(this.playerTranscriptService.getNumCards()),
          currentEngineService.getLanguageCode()
      );

      this.statsReportingService.recordStateCompleted(oldStateName);
      if (nextCard.isTerminal()) {
          this.statsReportingService.recordStateCompleted(nextCard.getStateName());
      }
      if (wasOldStateInitial && !this.explorationActuallyStarted) {
          this.statsReportingService.recordExplorationActuallyStarted(oldStateName);
          this.explorationActuallyStarted = true;
      }
  }

  // ====================================TRIGGER IF LEARNER STUCK===============================================================================.

  triggerIfLearnerStuckAction(): void {
    this.clearResponseTimeout();
    this.responseTimeout = setTimeout(() => {
        if (this.shouldRedirectToStuckState()) {
            this.handleStuckStateRedirection();
        } else if (this.shouldReleaseSolution()) {
            this.hintsAndSolutionManagerService.releaseSolution();
        }
    }, ExplorationPlayerConstants.WAIT_BEFORE_RESPONSE_FOR_STUCK_LEARNER_MSEC);
  }

  private clearResponseTimeout(): void {
      if (this.responseTimeout) {
          clearTimeout(this.responseTimeout);
          this.responseTimeout = null;
      }
  }

  private shouldRedirectToStuckState(): boolean {
      return (
          this.nextCardIfStuck &&
          this.nextCardIfStuck !== this.displayedCard
      );
  }

  private handleStuckStateRedirection(): void {
      this.playerTranscriptService.addNewResponseToExistingFeedback(
          this.translateService.instant('I18N_REDIRECTION_TO_STUCK_STATE_MESSAGE')
      );
      this.continueToReviseStateButtonIsVisible = true;
  }

  private shouldReleaseSolution(): boolean {
      return (
          this.solutionForState !== null &&
          this.numberOfIncorrectSubmissions >=
              ExplorationPlayerConstants.MAX_INCORRECT_ANSWERS_BEFORE_RELEASING_SOLUTION
      );
  }

  triggerIfLearnerStuckActionDirectly(): void {
    this.clearResponseTimeout();

    if (this.shouldRedirectToStuckState()) {
        this.handleStuckStateRedirection();
    } else if (this.shouldReleaseSolution()) {
        this.hintsAndSolutionManagerService.releaseSolution();
    }
  }

  triggerRedirectionToStuckState(): void {
    // Redirect the learner.
    this.nextCard = this.nextCardIfStuck;
    this.showInteraction = false;
    this.showPendingCard();
  }

  // ======================================================================================================================.

  getRecommendedExpTitleTranslationKey(explorationId: string): string {
    return this.i18nLanguageCodeService.getExplorationTranslationKey(
      explorationId,
      TranslationKeyType.TITLE
    );
  }

  isCorrectnessFooterEnabled(): boolean {
    return (
      this.correctnessFooterIsShown &&
      this.answerIsCorrect &&
      this.playerPositionService.hasLearnerJustSubmittedAnAnswer()
    );
  }

  skipCurrentQuestion(): void {
    this.explorationPlayerStateService.skipCurrentQuestion(nextCard => {
      this.nextCard = nextCard;
      this.showPendingCard();
    });
  }

  getExplorationLink(): string {
    if (
      this.recommendedExplorationSummaries &&
      this.recommendedExplorationSummaries[0]
    ) {
      if (!this.recommendedExplorationSummaries[0].id) {
        return '#';
      } else {
        let result = '/explore/' + this.recommendedExplorationSummaries[0].id;
        let urlParams = this.urlService.getUrlParams();
        let parentExplorationIds =
          this.recommendedExplorationSummaries[0].parentExplorationIds;

        let collectionIdToAdd = this.collectionId;
        let storyUrlFragmentToAdd = null;
        let topicUrlFragment = null;
        let classroomUrlFragment = null;
        // Replace the collection ID with the one in the URL if it
        // exists in urlParams.
        if (parentExplorationIds && urlParams.hasOwnProperty('collection_id')) {
          collectionIdToAdd = urlParams.collection_id;
        } else if (
          this.urlService.getPathname().match(/\/story\/(\w|-){12}/g) &&
          this.recommendedExplorationSummaries[0].nextNodeId
        ) {
          storyUrlFragmentToAdd =
            this.urlService.getStoryUrlFragmentFromLearnerUrl();
          topicUrlFragment =
            this.urlService.getTopicUrlFragmentFromLearnerUrl();
          classroomUrlFragment =
            this.urlService.getClassroomUrlFragmentFromLearnerUrl();
        } else if (
          urlParams.hasOwnProperty('story_url_fragment') &&
          urlParams.hasOwnProperty('node_id') &&
          urlParams.hasOwnProperty('topic_url_fragment') &&
          urlParams.hasOwnProperty('classroom_url_fragment')
        ) {
          topicUrlFragment = urlParams.topic_url_fragment;
          classroomUrlFragment = urlParams.classroom_url_fragment;
          storyUrlFragmentToAdd = urlParams.story_url_fragment;
        }

        if (collectionIdToAdd) {
          result = this.urlService.addField(
            result,
            'collection_id',
            collectionIdToAdd
          );
        }
        if (parentExplorationIds) {
          for (let i = 0; i < parentExplorationIds.length - 1; i++) {
            result = this.urlService.addField(
              result,
              'parent',
              parentExplorationIds[i]
            );
          }
        }
        if (storyUrlFragmentToAdd && this.storyNodeIdToAdd) {
          result = this.urlService.addField(
            result,
            'topic_url_fragment',
            topicUrlFragment
          );
          result = this.urlService.addField(
            result,
            'classroom_url_fragment',
            classroomUrlFragment
          );
          result = this.urlService.addField(
            result,
            'story_url_fragment',
            storyUrlFragmentToAdd
          );
          result = this.urlService.addField(
            result,
            'node_id',
            this.storyNodeIdToAdd
          );
        }
        return result;
      }
    }
  }

  /**
 * Handles the fatigue detection process after an answer submission. If the user is
 * submitting answers too quickly (based on the configured threshold), it will
 * display a message encouraging the user to take a break. This method is only active
 * if the system is not in preview mode.
 *
 * The method checks whether the user is submitting too fast, and if so, it triggers
 * the fatigue detection service to display the "take a break" message and prevent
 * further submissions. Additionally, it emits a feedback event to the exploration
 * player state service.
 *
 * @returns {void} - This method does not return any value. It performs side effects
 *                   related to fatigue detection and feedback display.
 */
  handleFatigueDetection(): void {
    if (!this.isInPreviewMode) {
      this.fatigueDetectionService.recordSubmissionTimestamp();
      if (this.fatigueDetectionService.isSubmittingTooFast()) {
        this.fatigueDetectionService.displayTakeBreakMessage();
        this.explorationPlayerStateService.onOppiaFeedbackAvailable.emit();
        return;
      }
    }
  }

  /**
   * Calculates the delay time (in milliseconds) to wait after a submission before
   * displaying feedback or transitioning to the next state/card. The delay is dependent
   * on several factors like whether the interaction is inline, if the exploration is
   * in diagnostic test mode, and the time elapsed since the server call.
   *
   * @param {number} timeAtServerCall - The timestamp (in milliseconds) when the server
   *                                     call was made for the answer submission.
   *
   * @returns {number} - The calculated delay time in milliseconds. The method ensures that
   *                     the delay is at least 1 millisecond, even if the calculated delay
   *                     is negative due to rapid server responses.
 */
  calculatePostSubmissionDelay(timeAtServerCall: number): number {
    let millisecsLeftToWait = 1.0;
    if (!this.displayedCard.isInteractionInline()) {
      // Do not wait if the interaction is supplemental -- there's
      // already a delay bringing in the help card.
      millisecsLeftToWait = 1.0;
    } else if (this.explorationPlayerStateService.isInDiagnosticTestPlayerMode()) {
      // Do not wait if the player mode is the diagnostic test. Since no
      // feedback will be presented after attempting a question so delaying
      // is not required.
      millisecsLeftToWait = 1.0;
    } else {
      millisecsLeftToWait = Math.max(
        ExplorationPlayerConstants.MIN_CARD_LOADING_DELAY_MSEC - (new Date().getTime() - timeAtServerCall),
        1.0
      );
    }
    return millisecsLeftToWait;
  }

  isHackyExpTitleTranslationDisplayed(explorationId: string): boolean {
    let recommendedExpTitleTranslationKey =
      this.getRecommendedExpTitleTranslationKey(explorationId);
    return (
      this.i18nLanguageCodeService.isHackyTranslationAvailable(
        recommendedExpTitleTranslationKey
      ) && !this.i18nLanguageCodeService.isCurrentLanguageEnglish()
    );
  }

  // ======================================================================================================================.

  isSubmitButtonDisabled(): boolean {
    let currentIndex = this.playerPositionService.getDisplayedCardIndex();
    // This check is added because it was observed that when returning
    // to current card after navigating through previous cards, using
    // the arrows, the Submit button was sometimes falsely disabled.
    // Also, since a learner's answers would always be in the current
    // card, this additional check doesn't interfere with its normal
    // working.
    if (!this.playerTranscriptService.isLastCard(currentIndex)) {
      return false;
    }
    return this.currentInteractionService.isSubmitButtonDisabled();
  }

  alwaysAskLearnerForAnswerDetails(): boolean {
    return this.explorationEngineService.getAlwaysAskLearnerForAnswerDetails();
  }

  getCanAskLearnerForAnswerInfo(): boolean {
    return this.learnerAnswerInfoService.getCanAskLearnerForAnswerInfo();
  }

  changeCard(index: number): void {
    this.playerPositionService.recordNavigationButtonClick();
    this.playerPositionService.setDisplayedCardIndex(index);
    this.explorationEngineService.onUpdateActiveStateIfInEditor.emit(
      this.playerPositionService.getCurrentStateName()
    );
    this.playerPositionService.changeCurrentQuestion(index);
  }

  isDisplayedCardCompletedInPrevSession(): boolean {
    return (
      this.displayedCard.getInteraction() &&
      this.prevSessionStatesProgress.indexOf(
        this.displayedCard.getStateName()
      ) !== -1
    );
  }

  recordLeaveForRefresherExp(refresherExpId: string | null): void {
    let editorPreviewMode = this.contextService.isInExplorationEditorPage();
    if (!editorPreviewMode) {
      this.statsReportingService.recordLeaveForRefresherExp(
        this.playerPositionService.getCurrentStateName(),
        refresherExpId
      );
    }
  }

  isSupplementalCardNonempty(card: StateCard): boolean {
    return (card && !card.isInteractionInline());
  }

  isLearnAgainButton(): boolean {
    let conceptCardIsBeingShown =
      this.displayedCard.getStateName() === null &&
      !this.explorationPlayerStateService.isInQuestionMode();
    if (conceptCardIsBeingShown) {
      return false;
    }
    let interaction = this.displayedCard.getInteraction();

    if (!interaction.id) {
      // An editor might also try to view preview tab without adding
      // interaction to concept card.
      return false;
    }

    if (INTERACTION_SPECS[interaction.id].is_linear) {
      return false;
    }
    return this.pendingCardWasSeenBefore && !this.answerIsCorrect;
  }

  isCurrentCardAtEndOfTranscript(): boolean {
    return this.playerTranscriptService.isLastCard(
      this.playerPositionService.getDisplayedCardIndex()
    );
  }

  getStaticImageUrl(imagePath: string): string {
    return this.urlInterpolationService.getStaticImageUrl(imagePath);
  }

  isSupplementalNavShown(): boolean {
    if (
      this.displayedCard.getStateName() === null &&
      !this.explorationPlayerStateService.isInQuestionMode()
    ) {
      return false;
    }
    let interaction = this.displayedCard.getInteraction();
    return (
      Boolean(interaction.id) &&
      INTERACTION_SPECS[interaction.id].show_generic_submit_button &&
      this.isCurrentCardAtEndOfTranscript()
    );
  }

  // ========================================NAVIGATE TO DISPLAYED CARD===========================================================================.

  // Navigates to the currently-active card, and resets the
  // 'show previous responses' setting.
  navigateToDisplayedCard(): void {
    const index = this.playerPositionService.getDisplayedCardIndex();
    this.displayedCard = this.playerTranscriptService.getCard(index);

    if (this.shouldRecordCheckpoint(index)) {
      this.recordCheckpoint();
    }

    this.playerPositionService.onActiveCardChanged.emit();
    this.audioPlayerService.onAutoplayAudio.emit();

    this.autogeneratedAudioPlayerService.cancel();
    this.setFocusOnCard(index);
  }

  private shouldRecordCheckpoint(index: number): boolean {
    return (
      index > 0 &&
      !this.isIframed &&
      !this.editorPreviewMode &&
      !this.explorationPlayerStateService.isInQuestionPlayerMode() &&
      !this.explorationPlayerStateService.isInDiagnosticTestPlayerMode()
    );
  }

  private recordCheckpoint(): void {
    const currentState = this.explorationEngineService.getState();
    const currentStateName = currentState.name;

    if (
      currentState.cardIsCheckpoint &&
      !this.visitedStateNames.includes(currentStateName) &&
      !this.prevSessionStatesProgress.includes(currentStateName)
    ) {
      this.readOnlyExplorationBackendApiService
        .loadLatestExplorationAsync(this.explorationId)
        .then(response => {
          this.explorationPlayerStateService.setLastCompletedCheckpoint(currentStateName);
          this.editableExplorationBackendApiService.recordMostRecentlyReachedCheckpointAsync(
            this.explorationId,
            response.version,
            currentStateName,
            this.isLoggedIn,
            this.explorationPlayerStateService.getUniqueProgressUrlId()
          );
        });
      this.updateVisitedStateName(currentStateName);
    }
  }

  private setFocusOnCard(index: number): void {
    const focusLabel = this.nextFocusLabel && this.playerTranscriptService.isLastCard(index)
      ? this.nextFocusLabel
      : this.getContentFocusLabel(index);

    this.focusManagerService.setFocusIfOnDesktop(focusLabel);
  }

  // ==============================================ANIMATE CARDS===========================================================================.

  animateToTwoCards(doneCallback: () => void): void {
    this.isAnimatingToTwoCards = true;
    setTimeout(
      () => {
        this.isAnimatingToTwoCards = false;
        if (doneCallback) {
          doneCallback();
        }
      },
      ExplorationPlayerConstants.TIME_NUM_CARDS_CHANGE_MSEC + ExplorationPlayerConstants.TIME_FADEIN_MSEC + ExplorationPlayerConstants.TIME_PADDING_MSEC
    );
  }

  animateToOneCard(doneCallback: () => void): void {
    this.isAnimatingToOneCard = true;
    setTimeout(() => {
      this.isAnimatingToOneCard = false;
      if (doneCallback) {
        doneCallback();
      }
    }, ExplorationPlayerConstants.TIME_NUM_CARDS_CHANGE_MSEC);
  }

  // ========================================Methods For Variables=========================================================.

  updateVisitedStateName(stateName: string): void {
    this.visitedStateNames.push(stateName);
  }

  getVisitedStateNames(): string[] {
    return this.visitedStateNames;
  }

  updatedisplayedCard(card: StateCard): void {
    this.displayedCard = card;
  }

  getdisplayedCard(): StateCard {
    return this.displayedCard;
  }

  getIsAnimatingToTwoCards(): boolean {
    return this.isAnimatingToTwoCards;
  }

  getIsAnimatingToOneCard(): boolean {
    return this.isAnimatingToOneCard;
  }

  getProgressClearanceMessageIsShowed(): boolean {
    return this.progressClearanceMessageIsShowed;
  }

  getChapterIsCompletedForTheFirstTime(): boolean {
    return this.chapterIsCompletedForTheFirstTime;
  }

  updateStoryNodeIdToAdd(updatedNode: string): void {
    this.storyNodeIdToAdd = updatedNode;
  }

  getStoryNodeIdToAdd(): string {
    return this.storyNodeIdToAdd;
  }

  updateCompletedChaptersCount(updatedChapterCount: number | undefined): void {
    this.completedChaptersCount = updatedChapterCount;
  }

  getCompletedChaptersCount(): number | undefined {
    return this.completedChaptersCount;
  }

  updateRecommendedExplorationSummaries(updatedSummary: LearnerExplorationSummary[]): void {
    this.recommendedExplorationSummaries = updatedSummary;
  }

  getRecommendedExplorationSummaries(): LearnerExplorationSummary[] {
    return this.recommendedExplorationSummaries;
  }

  getInStoryMode(): boolean {
    return this.inStoryMode;
  }

  getParentExplorationIds(): string[] {
    return this.parentExplorationIds;
  }

  getIsRefresherExploration(): boolean {
    return this.isRefresherExploration;
  }

  updateMostRecentlyReachedCheckpoint(updatedCheckpoint: string): void {
    this.mostRecentlyReachedCheckpoint = updatedCheckpoint;
  }

  getMostRecentlyReachedCheckpoint(): string {
    return this.mostRecentlyReachedCheckpoint;
  }

  updatePrevSessionStatesProgress(updatedSessionState: string[]): void {
    this.prevSessionStatesProgress = updatedSessionState;
  }

  getPrevSessionStatesProgress(): string[] {
    return this.prevSessionStatesProgress;
  }

  updateNextFocusLabel(updatedLabel: string | null): void {
    this.nextFocusLabel = updatedLabel;
  }

  getNextFocusLabel(): string | null {
    return this.nextFocusLabel;
  }

  updateNextCard(updatedCard: StateCard): void {
    this.nextCard = updatedCard;
  }

  getNextCard(): StateCard {
    return this.nextCard;
  }

  updateHasFullyLoaded(updatedLoadStatus: boolean): void {
    this.hasFullyLoaded = updatedLoadStatus;
  }

  getHasFullyLoaded(): boolean {
    return this.hasFullyLoaded;
  }

  updateHasInteractedAtLeastOnce(updatedInteractedStatus: boolean): void {
    this.hasInteractedAtLeastOnce = updatedInteractedStatus;
  }

  getHasInteractedAtLeastOnce(): boolean {
    return this.hasInteractedAtLeastOnce;
  }

  updateStartCardChangeAnimation(updatedAnimationStatus: boolean): void {
    this.startCardChangeAnimation = updatedAnimationStatus;
  }

  getStartCardChangeAnimation(): boolean {
    return this.startCardChangeAnimation;
  }

  updateQuestionSessionCompleted(updatedSessionStatus: boolean): void {
    this.questionSessionCompleted = updatedSessionStatus;
  }

  getQuestionSessionCompleted(): boolean {
    return this.questionSessionCompleted;
  }

  updatePendingCardWasSeenBefore(updatedCardStatus: boolean): void {
    this.pendingCardWasSeenBefore = updatedCardStatus;
  }

  getPendingCardWasSeenBefore(): boolean {
    return this.pendingCardWasSeenBefore;
  }

  updateAnswerIsCorrect(updatedAnswerStatus: boolean): void {
    this.answerIsCorrect = updatedAnswerStatus;
  }

  getAnswerIsCorrect(): boolean {
    return this.answerIsCorrect;
  }

  updateMoveToExploration(updatedMoveStatus: boolean): void {
    this.moveToExploration = updatedMoveStatus;
  }

  getMoveToExploration(): boolean {
    return this.moveToExploration;
  }

  updateConceptCard(updatedCard: ConceptCard): void {
    this.conceptCard = updatedCard;
  }

  getConceptCard(): ConceptCard {
    return this.conceptCard;
  }

  updateAnswerIsBeingProcessed(updatedAnswerStatus: boolean): void {
    this.answerIsBeingProcessed = updatedAnswerStatus;
  }

  getAnswerIsBeingProcessed(): boolean {
    return this.answerIsBeingProcessed;
  }

  updateNumberOfIncorrectSubmissions(updatedSubmissionCount: number): void {
    this.numberOfIncorrectSubmissions = updatedSubmissionCount;
  }

  getNumberOfIncorrectSubmissions(): number {
    return this.numberOfIncorrectSubmissions;
  }

  getRedirectToRefresherExplorationConfirmed(): boolean {
    return this.redirectToRefresherExplorationConfirmed;
  }

  updateExplorationActuallyStarted(updatedStartedStatus: boolean): void {
    this.explorationActuallyStarted = updatedStartedStatus;
  }

  getExplorationActuallyStarted(): boolean {
    return this.explorationActuallyStarted;
  }

  updateNextCardIfStuck(nextCard: StateCard): void {
    this.nextCardIfStuck = nextCard;
  }

  getNextCardIfStuck(): StateCard {
    return this.nextCardIfStuck;
  }

  updateContinueToReviseStateButtonIsVisible(updatedButtonStatus: boolean): void {
    this.continueToReviseStateButtonIsVisible = updatedButtonStatus;
  }

  updateSolutionForState(updatedSolution: Solution): void {
    this.solutionForState = updatedSolution;
  }

  getShowInteraction(): boolean {
    return this.showInteraction;
  }

  updateCorrectnessFooterIsShown(updatedFooterStatus: boolean): void {
    this.correctnessFooterIsShown = updatedFooterStatus;
  }

  getCollectionSummary(): string[] | null {
    return this.collectionSummary;
  }
}
